"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { Store, persistor } from "@/redux/Store";
import { PersistGate } from "redux-persist/integration/react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={Store}>
      <PersistGate persistor={persistor} loading={<>loading...</>}>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </PersistGate>
    </Provider>
  );
}
